# Generated by Django 3.0.6 on 2020-07-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Hindi', 'Hindi'), ('English', 'English'), ('Computer', 'Computer'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], max_length=20)),
                ('start_time', models.CharField(choices=[('8:30', '8:30'), ('9:30', '9:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('2:00', '2:00'), ('3:00', '3:00'), ('4:00', '4:00')], max_length=20)),
                ('end_time', models.CharField(choices=[('9:30', '9:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('3:00', '3:00'), ('4:00', '4:00'), ('5:00', '5:00')], max_length=20)),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
    ]
