# Generated by Django 3.0.6 on 2020-07-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Days'},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.CreateModel(
            name='TimeTableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Hindi', 'Hindi'), ('English', 'English'), ('Computer', 'Computer'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], max_length=20)),
                ('start_time', models.CharField(choices=[('8:30', '8:30'), ('9:30', '9:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('2:00', '2:00'), ('3:00', '3:00'), ('4:00', '4:00')], max_length=20)),
                ('end_time', models.CharField(choices=[('9:30', '9:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('3:00', '3:00'), ('4:00', '4:00'), ('5:00', '5:00')], max_length=20)),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.TimeTable')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
    ]
